### ISSUE TITLE
Cannot arm

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#12]
Hi,
This is with ver. 1.1.0
I have only two sensors configured: one entry door sensor and a movement one.
When I try to arm, I get this in the log:

`2020-11-16 18:02:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139730749224128] 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
await result
File "/config/custom_components/alarmo/alarm_control_panel.py", line 265, in async_alarm_arm_away
await self.async_arm(STATE_ALARM_ARMED_AWAY)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 428, in async_arm
await self.async_update_state(STATE_ALARM_ARMING)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 393, in async_update_state
await self.automations.async_handle_state_update(state=state, last_state=last_state)
File "/config/custom_components/alarmo/automations.py", line 71, in async_handle_state_update
await self.async_execute_automation(automation_id)
File "/config/custom_components/alarmo/automations.py", line 108, in async_execute_automation
changed_by_string = self.async_format_sensor_info(changed_by)
File "/config/custom_components/alarmo/automations.py", line 127, in async_format_sensor_info
for (entity_id, status) in open_sensors.items():
AttributeError: 'NoneType' object has no attribute 'items'
2020-11-16 18:02:48 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state armed_away from state arming.
2020-11-16 18:02:52 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state armed_home from state arming.`

If you need more data, please ask me.

Thanks for your interest.

**Comment by nielsfaber** [comment]
About this error:
``` 
[custom_components.alarmo.alarm_control_panel] Cannot go to state armed_home from state arming.
```

Arming is only allowed from `disarmed` state (not from state `arming`).

Seems like you try to arm while it is already in progress.
Are you arming through an automation or something?


The rest of the description is hard to read for me.
Please format the log in a better way.

**Comment by tremebundo** [comment]
This is the log just after rebooting HA and hit the button "Arm away":

`2020-11-16` 19:35:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139850350210256] 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
await result
File "/config/custom_components/alarmo/alarm_control_panel.py", line 265, in async_alarm_arm_away
await self.async_arm(STATE_ALARM_ARMED_AWAY)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 428, in async_arm
await self.async_update_state(STATE_ALARM_ARMING)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 393, in async_update_state
await self.automations.async_handle_state_update(state=state, last_state=last_state)
File "/config/custom_components/alarmo/automations.py", line 71, in async_handle_state_update
await self.async_execute_automation(automation_id)
File "/config/custom_components/alarmo/automations.py", line 108, in async_execute_automation
changed_by_string = self.async_format_sensor_info(changed_by)
File "/config/custom_components/alarmo/automations.py", line 127, in async_format_sensor_info
for (entity_id, status) in open_sensors.items():
AttributeError: 'NoneType' object has no attribute 'items'`

**Comment by tremebundo** [comment]
Then, I press again "Arm away", the log say:

`2020-11-16 19:47:26 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state armed_home from state arming.`

But I am still waiting for more than ten minutes now, and never get armed, if look to the card.

**Comment by tremebundo** [comment]
Found it.
I configured a notification for the change to "arming". After disabling it. It goes to "armed".
Something wrong with the notification...

**Comment by nielsfaber** [comment]
Ah that makes more sense.
Apparently something crashed while arming.
As a result the alarm state is stuck in arming, and arming again is not possible.

I will check tomorrow if I can reproduce the problem with the notification.
Did you configure anything fancy or just use the UI editor form?

**Comment by tremebundo** [comment]
No, no special thing. Just initial trashing. But I deleted the configured action.I think it was only a notification: send a message to my phone.

**Comment by nielsfaber** [comment]
I found the problem that causes this and fixed it.
Will release an update soon.

**Comment by nielsfaber** [comment]
Please update to V1.1.1 (requires reboot), and test if it solves the problem.
If so, you can close the issue.

**Comment by nielsfaber** [comment]
OK great! It was really simple stuff i had to change actually...
Too bad that the result was catastrophic 😅 

Let me know if you run into more issues!

**Comment by tremebundo** [comment]
Installed 1.1.1 and the problem is gone. Good work. Closed.

**Comment by aleksandrov1995** [comment]
I am having what may be a strange thing (i did a hard refresh this time!), the butons for requiring pincode for arming/disarming are inverted for me. E.g. when the reqire pin for arming is on, it requires pin for disarming, but not for arming. And the same happens if i flip the other one on, it requires pin for disarming, but not for arming.

I hope all this makes sense.

**Comment by nielsfaber** [comment]
@aleksandrov1995: good catch! 
I saw their are indeed swapped in my code.
So:
- when you ask to disarm, and no arm code is required, the validation is skipped.
- when you ask to arm, and no disarm code is required, the validation is skipped.

In code:
```
        if state == STATE_ALARM_DISARMED and not self._config[ATTR_CODE_ARM_REQUIRED]:
            return True
        elif state != STATE_ALARM_DISARMED and not self._config[ATTR_CODE_DISARM_REQUIRED]:
            return True
```

These should have been they other way around ofcourse.
It will be updated in the next release, thanks for reporting!
