### ISSUE TITLE
Error when changing code

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#13]
I'm testing with 1.1. Looks like I may have added my user with the wrong pin code, because I can't arm currently.

So tried to change the code (entered what I think was the old code, but most likely wrong code, and new code x2) and got the following error:
Something went wrong!

Response error: 500

Please report the bug.

Log details:
Logger: aiohttp.server
Source: custom_components/alarmo/__init__.py:155
First occurred: 9:21:32 AM (3 occurrences)
Last logged: 9:31:46 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/config/custom_components/alarmo/websockets.py", line 190, in post
    coordinator.async_update_user_config(user_id, data)
  File "/config/custom_components/alarmo/__init__.py", line 138, in async_update_user_config
    elif not self.async_authenticate_user(data[ATTR_OLD_CODE], user_id):
  File "/config/custom_components/alarmo/__init__.py", line 155, in async_authenticate_user
    if not user[ATTR_CODE] and not code:
TypeError: 'UserEntry' object is not subscriptable

**Comment by nielsfaber** [comment]
I am hopeful I can reproduce this issue.
Will try that tomorrow, seems like an easy fix once I catch the error

**Comment by nielsfaber** [comment]
I identified the problem and fixed it.
I will make a new release soon.

**Comment by nielsfaber** [comment]
Please update to V1.1.1 and test if it solves the problem.
If so, you can close the issue.

You will need to restart HA to see the change.

**Comment by stefanolson** [comment]
Yup. Sorted now. Thanks
