### ISSUE TITLE
potential upcoming change in next release

### ISSUE THREAD

**Issue by aidbish** [nielsfaber/alarmo#189]
i run dev releases and have noticed that the last few releases of them have the following error for alarmo, there could be a potential change you may need to be aware of

2021-04-28 17:21:15 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
  await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'

**Comment by aidbish** [comment]
duplicate of https://github.com/nielsfaber/alarmo/issues/186

closing as known issue
