### ISSUE TITLE
Error while saving entry time. (0.117.0b6)

### ISSUE THREAD

**Issue by tteck** [nielsfaber/alarmo#2]
Logger: homeassistant.components.websocket_api.http.connection.139909452651920
Source: custom_components/alarmo/alarm_control_panel.py:465
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:28:11 AM (2 occurrences)
Last logged: 2:28:17 AM

'leave'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 465, in async_edit_config
    self._config[ATTR_DELAYS][event][mode] = val
KeyError: 'leave'

**Comment by tteck** [comment]
I think that it has something to do with the upcoming 117.0
It worked with beta 117.0b4 (I think that was the version at install), but not with 117.0b6

**Comment by nielsfaber** [comment]
I will check it out this weekend.
Should be a simple fix.

I don’t think it is HA related, just my programming skills.
Thanks for reporting

**Comment by nielsfaber** [comment]
Does this problem still occur for you?
Or is it solved in the mean time?

**Comment by tteck** [comment]
It still occurs.

**Comment by tteck** [comment]
When you release the current "major update" I'm hopeful

**Comment by nielsfaber** [comment]
v1.1.0 is hereby released.
Since the storage is completely changed it would surprise me if you still have this error after updating.

**Comment by tteck** [comment]
v1.1.0 solved issue
