### ISSUE TITLE
Modifying and then saving notification produces error 400

### ISSUE THREAD

**Issue by muddro1** [nielsfaber/alarmo#238]
### Checklist
- [X ] I checked for similar existing issues (both open and closed) before posting.
- [X ] I am running the latest version.

### Expected behavior
To be able to save the notification

### Actual behavior
Recieve: Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']

Response error: 400

Please report the bug.

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by Ixian** [comment]
I'm seeing similar behavior but it's generating an Error 500 when attempting to disable/enable actions.

Log:
[code]
Logger: aiohttp.server
Source: custom_components/alarmo/store.py:171
Integration: Alarmo (documentation, issues)
First occurred: 10:04:32 AM (4 occurrences)
Last logged: 10:06:11 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/config/custom_components/alarmo/websockets.py", line 332, in post
    coordinator.async_update_automation_config(automation_id, data)
  File "/config/custom_components/alarmo/__init__.py", line 266, in async_update_automation_config
    self.store.async_update_automation(automation_id, data)
  File "/config/custom_components/alarmo/store.py", line 561, in async_update_automation
    new = self.automations[automation_id] = attr.evolve(old, **parse_automation_entry(changes))
  File "/config/custom_components/alarmo/store.py", line 171, in parse_automation_entry
    "triggers": list(map(create_trigger_entity, data["triggers"])),
KeyError: 'triggers'
[/code]

**Comment by nielsfaber** [comment]
This problem is solved in v1.6.2 i think.
Could you update and give it a try?
