### ISSUE TITLE
Alexa notify.alexa_media

### ISSUE THREAD

**Issue by morenonew2** [nielsfaber/alarmo#276]
Is not possible to use alexa_media like TTS notify
this is my error

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:195
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:51:05 (5 occurrences)
Last logged: 17:53:55

[1558717512] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/notify.py", line 195, in async_send_message
    for target in targets:
TypeError: 'NoneType' object is not iterable

Thank

**Comment by nielsfaber** [comment]
Your error doesn’t show any problem caused by alarmo.
Therefore I cannot help you.

**Comment by francois-nitenberg** [comment]
@nielsfaber , I have the same error. I believe the Alarmo front-end generate an invalid object for media_player.
