### ISSUE TITLE
Unable to arm custom after latest update

### ISSUE THREAD

**Issue by Toukite** [nielsfaber/alarmo#334]
Hello,

After updating everything this morning, I have below the error message after calling following service:
```
service: alarmo.arm
data:
  mode: custom
  entity_id: alarm_control_panel.xxx
```

```
2021-11-29 08:41:29 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'armed_custom'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 685, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 351, in async_service_arm_handler
    await self.async_handle_arm_request(
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 366, in async_handle_arm_request
    not (const.MODES_TO_SUPPORTED_FEATURES[arm_mode] & self.supported_features) or
KeyError: 'armed_custom'
2021-11-29 08:41:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547083385056] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 685, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 351, in async_service_arm_handler
    await self.async_handle_arm_request(
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 366, in async_handle_arm_request
    not (const.MODES_TO_SUPPORTED_FEATURES[arm_mode] & self.supported_features) or
KeyError: 'armed_custom'
```

I don't think I see something related to this on the breaking changes list. Can you please help ?

Thanks !

**Comment by nielsfaber** [comment]
Woops, my bad. This was unintentional.
You could use `armed_custom_bypass` as mode, it would work the same.
I will have to make some change to allow `custom` as input again.

**Comment by Toukite** [comment]
Ok thanks !
This is working with armed_custom_bypass

Note that this is also breaking automations GUI when calling the service, we have to force yaml mode since drop-down only allows this:
![image](https://user-images.githubusercontent.com/42780622/143833409-50760214-a6df-459d-88bb-d8cb3776abda.png)

Question: are other modes impacted too ?

**Comment by nielsfaber** [comment]
The fix is on its way https://github.com/nielsfaber/alarmo/commit/62a6672ac9ec8d7c2e00259ab89df1be6a8c0bb6
I will update you once I released the change.

> Question: are other modes impacted too ?

No, only input 'custom' is not processed correctly.

**Comment by nielsfaber** [comment]
Can you update alarmo to v1.8.1? This should solve the problem.
Please close the issue if it works OK now.
