### ISSUE TITLE
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated'

### ISSUE THREAD

**Issue by jazzyisj** [nielsfaber/alarmo#336]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

- HA v2021.11.5
- Started after update to latest version v1.80
- Alarmo card has been updated to latest version.
- Errors do no seem to be affecting Alarmo operation.  Everything working normally except log errors.

### Expected behavior
No log errors on Alarmo events.

### Actual behavior
Log errors whenever Alarmo state changes (arming, disarming, pending, triggered etc)

```
2021-11-29 00:31:06 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', '1616293922', {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 00:31:06 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1616293922', 'disarmed', 'armed_home')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 00:31:06 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', '1632207454', {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 00:31:06 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1632207454', 'disarmed', 'armed_home')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 00:31:06 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', None, {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```
```
2021-11-29 09:37:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1632207454', 'pending', 'triggered')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 09:37:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': (None, 'pending', 'triggered')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

### Steps to Reproduce
Change Alarmo state.

**Comment by nielsfaber** [comment]
I cannot reproduce your problem.
I am able arm/disarm/trigger the alarm without seeing the error. Also I have MQTT enabled.
Could you please provide more info regarding the situation in which this occurs?

**Comment by nielsfaber** [comment]
Ah I think this is because you are using an older version of HA.
I am running HA 2021.12.0.dev.
This Wesnesday HA 2021.12 will be released, which comes with changes in the MQTT implementation.
I expect the issue will resolve itself by updating (either to the dev branch or wait for wednesday).
I rolled back my HA version to 2021.11 and could reproduce your error. I can also confirm the error is harmless, the MQTT data is still sent correctly.

**Comment by jazzyisj** [comment]
- I have no Alarmo automations, I have disabled all of my HA alarm related automations
- Error occurs during startup before HA starts
- Error occurs every time alarm is armed/disarmed 
- Error occurs whether MQTT is enabled or not.  See log below for error when MQTT is disabled.
- Error occurs whether the alarm is armed/disarmed with Alarmo lovelace card or HA alarm control panel.
- homeassistant.util.logging: debug offers no further detail in logs
- Rolling back to v1.76 resolves the error logs

The following errors occur from going from state disarmed to armed_home (armed with Alarmo keypad) with MQTT enabled

```
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', '1616293922', {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1616293922', 'disarmed', 'armed_home')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', '1632207454', {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1632207454', 'disarmed', 'armed_home')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('arm', None, {'arm_mode': 'armed_home', 'delay': 0})
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 152, in async_handle_event
    hass.async_create_task(mqtt.async_publish(self.hass, topic, payload))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:36:19 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': (None, 'disarmed', 'armed_home')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

```
The following errors occur going from armed_home to disarmed with MQTT disabled
2021-11-29 14:38:30 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1616293922', 'armed_home', 'disarmed')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:38:30 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1632207454', 'armed_home', 'disarmed')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
2021-11-29 14:38:30 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': (None, 'armed_home', 'disarmed')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 82, in async_alarm_state_changed
    hass.async_create_task(mqtt.async_publish(self.hass, topic, message, retain=True))
  File "/usr/src/homeassistant/homeassistant/core.py", line 393, in async_create_task
    task: asyncio.Task = self.loop.create_task(target)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

**Comment by jazzyisj** [comment]
Bah!  We crossed paths.  I just killed a couple hours trying to debug..lol.  Thanks for looking into it.

I'll leave issue open until update it out so others will see.

**Comment by nielsfaber** [comment]
I'm sorry for this situation 😅 
I just try to be ahead of breaking changes in HA, without the fix the MQTT functionality in Alarmo would stop working completely once you update to HA 2021.12. 
They didn't give me much choice here.. 
But I didn't realise that the changes are not backwards-compatible (hence your error), sorry for that!
