### ISSUE TITLE
1.3.0 ERROR 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by tteck** [nielsfaber/alarmo#34]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alarmo/alarm_control_panel.py:289
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:19:19 PM (3 occurrences)
Last logged: 12:19:48 PM

[140178131266768] 'bool' object is not subscriptable
[140178161299408] 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 536, in _handle_entity_call
    await result
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 305, in async_alarm_arm_home
    await self._async_handle_arm_request(STATE_ALARM_ARMED_HOME, code, skip_code)
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 289, in _async_handle_arm_request
    elif res[ATTR_IS_OVERRIDE_CODE]:
TypeError: 'bool' object is not subscriptable

**Comment by nielsfaber** [comment]
whoops!

**Comment by nielsfaber** [comment]
I made an emergency release v1.3.1 for this.
I overlooked this situation.

**Comment by tteck** [comment]
Seems ok now.
Fast release!
