### ISSUE TITLE
Disarm Master is not possible with Version 1.8.4

### ISSUE THREAD

**Issue by Borcon** [nielsfaber/alarmo#390]
### Alarmo Version

1.8.4

### HA Version

2022.2.3

### Bug description

It's not possible to disarm the Alarmo Master.
Only possible to disarm each area.

### Steps to reproduce

If Alarmo Master is armed home or armed away, disarm is not possible.

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alarmo/alarm_control_panel.py:344
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:52:42 (8 occurrences)
Last logged: 17:58:39

[139823815729552] 'NoneType' object has no attribute 'format'
[139823637633632] 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 308, in async_service_disarm_handler
    await self.async_alarm_disarm(
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 941, in async_alarm_disarm
    res = await super().async_alarm_disarm(code, skip_code)
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 344, in async_alarm_disarm
    _LOGGER.info("Alarm '{}' is disarmed.").format(self.name)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by nielsfaber** [comment]
Thank you for reporting this. 
I saw this is caused by a very minor typo (with big consequences), the fix is on its way: https://github.com/nielsfaber/alarmo/commit/340378035451b873c2d3209bd07f27b3cc315ea4

This is a critical issue to me so I will make a release asap to fix this.

**Comment by Borcon** [comment]
Thanks for this great integration 👍

**Comment by nielsfaber** [comment]
Release v1.8.5 is out which fixes this.
