### ISSUE TITLE
HA v2022.6.0 beta - WARNING deprecated `async_get_registry`

### ISSUE THREAD

**Issue by jazzyisj** [nielsfaber/alarmo#475]
### Alarmo Version

v1.9.3

### HA Version

2022.6.0b0

### Bug description

Warning in log re deprecated `async_get_registry`.

### Relevant log output

```shell
WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 58: device_registry = await dr.async_get_registry(hass)
```

**Comment by hvorragend** [comment]
With 2022.6 beta I have more problems using Alarmo:


```
Logger: homeassistant.util.logging
Source: util/logging.py:116 
First occurred: 18:22:42 (1 occurrences) 
Last logged: 18:22:42

Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1634207442', 'armed_away', 'pending') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 180, in async_execute_automation parts.append(await self.async_get_open_sensor_string(entity_id, status, lang)) File "/config/custom_components/alarmo/automations.py", line 234, in async_get_open_sensor_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 's' not found.
```

**Comment by drizuid** [comment]
I'm on 2022.6 stable and only get the async_get_registry issue, the line 58 as the OP shows. non-breaking currently though, just a warning.

**Comment by javiges** [comment]
> I'm on 2022.6 stable and only get the async_get_registry issue, the line 58 as the OP shows. non-breaking currently though, just a warning.

I have the same problem, but alarm works

**Comment by PerSterin** [comment]
I'm on 2022.6 stable, non-breaking currently though, just a warning.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 10:13:31 (1 occurrences)
Last logged: 10:13:31
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 58: device_registry = await dr.async_get_registry(hass)

**Comment by Masterz69** [comment]
On 2022.6.1. same message:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 11:50:52 (3 occurrences)
Last logged: 11:55:56

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 58: device_registry = await dr.async_get_registry(hass)
```

**Comment by nielsfaber** [comment]
This issue should be solved by updating to v1.9.4. 
@jazzyisj : please close the issue after confirming the problem is solved.

**Comment by tomlut** [comment]
Can confirm, it's fixed.

**Comment by jazzyisj** [comment]
All cool in school.  Thanks @nielsfaber!
