### ISSUE TITLE
HA 2022.6 Actions and notifications not working

### ISSUE THREAD

**Issue by Strangehadron** [nielsfaber/alarmo#485]
### Alarmo Version

1.9.3

### HA Version

2022.6.0

### Bug description

Hi,
Since the 2022.6 update alarmo isn't running all of my notifications or actions (made in alarmo actions tab)

Notifications:
- I've a notification on my phone when my alarm is armed, not working. 🔴 
- Another one when i unarm the alarm, that one is working. ✅ 

Actions:
- I've an action that run a script (lamp flash in red) when the alarm is triggered, not working anymore. 🔴 

I've test the script it's working so the problem is runing it in alarmo. I've not change anything in alarmo and it was working good.

### Steps to reproduce

- Arm the alarm (via automation based on presence or manualy)
- No notifications coming for arming the alarm.
- trigger the alarm, actions not running.``

Thanks for your help. 👍 

### Relevant log output

shell

> Logger: homeassistant.util.logging
> Source: util/logging.py:116 
> First occurred: 07:43:30 (3 occurrences) 
> Last logged: 08:01:27
> 
> Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1628345743', 'arming', 'armed_away') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 199, in async_execute_automation arm_mode = await self.async_get_arm_mode_string(alarm_entity.arm_mode, lang) File "/config/custom_components/alarmo/automations.py", line 283, in async_get_arm_mode_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'm' not found.
> Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1628345743', 'pending', 'triggered') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 180, in async_execute_automation parts.append(await self.async_get_open_sensor_string(entity_id, status, lang)) File "/config/custom_components/alarmo/automations.py", line 234, in async_get_open_sensor_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'i' not found.
> 
>

**Comment by Alexisc21** [comment]
Hi,
I get exactly the same behavior.

**Comment by IvanBrazza** [comment]
For me actions are working, but notifications aren’t. Same HA/Alarmo versions, slightly different log output:

```
2022-06-02 15:04:02 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('failed_to_arm', '1632501527', {'open_sensors': {'binary_sensor.dining_room_window_sensor_access_control_window_door_is_open': 'open'}, 'context_id': None})                                   
 Traceback (most recent call last):                                                                                                                                 
   File "/config/custom_components/alarmo/automations.py", line 138, in async_handle_event                                                                          
     await self.async_execute_automation(automation_id, alarm_entity)                                                                                               
   File "/config/custom_components/alarmo/automations.py", line 180, in async_execute_automation                                                                    
     parts.append(await self.async_get_open_sensor_string(entity_id, status, lang))                                                                                 
   File "/config/custom_components/alarmo/automations.py", line 234, in async_get_open_sensor_string                                                                
     translations = await self.hass.helpers.translation.async_get_translations(                                                                                     
   File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations                                                          
     cached = await cache.async_fetch(language, category, components)                                                                                               
   File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch                                                                      
    await self._async_load(language, components_to_load)                                                                                                           
   File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load                                                                     
     for translation_strings in await asyncio.gather(                                                                                                               
   File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings                                                     
     await gather_with_concurrency(                                                                                                                                 
   File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency                                                                 
     return await gather(                                                                                                                                           
   File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task                                                                                
     return await task                                                                                                                                              
   File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration                                                                        
     integration = await _async_get_integration(hass, domain)                                                                                                       
   File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration                                                                       
     raise IntegrationNotFound(domain)                                                                                                                              
 homeassistant.loader.IntegrationNotFound: Integration 'o' not found.
```

**Comment by wiredwiz** [comment]
I also receive the same behavior.  The disarm notification works, but trigger actions and notifications never fire.  Here is the error log I get from an alarm trigger

```
Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 10:27:35 AM (12 occurrences)
Last logged: 11:04:04 AM

Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1652935251', 'disarmed', 'armed_vacation') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 199, in async_execute_automation arm_mode = await self.async_get_arm_mode_string(alarm_entity.arm_mode, lang) File "/config/custom_components/alarmo/automations.py", line 283, in async_get_arm_mode_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'o' not found.
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1652935251', 'arming', 'armed_vacation') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 199, in async_execute_automation arm_mode = await self.async_get_arm_mode_string(alarm_entity.arm_mode, lang) File "/config/custom_components/alarmo/automations.py", line 283, in async_get_arm_mode_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'n' not found.
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1652935251', 'pending', 'triggered') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 180, in async_execute_automation parts.append(await self.async_get_open_sensor_string(entity_id, status, lang)) File "/config/custom_components/alarmo/automations.py", line 234, in async_get_open_sensor_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'o' not found.
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1652935251', 'arming', 'armed_away') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 199, in async_execute_automation arm_mode = await self.async_get_arm_mode_string(alarm_entity.arm_mode, lang) File "/config/custom_components/alarmo/automations.py", line 283, in async_get_arm_mode_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'n' not found.
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1652935251', 'pending', 'triggered') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 180, in async_execute_automation parts.append(await self.async_get_open_sensor_string(entity_id, status, lang)) File "/config/custom_components/alarmo/automations.py", line 234, in async_get_open_sensor_string translations = await self.hass.helpers.translation.async_get_translations( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations cached = await cache.async_fetch(language, category, components) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch await self._async_load(language, components_to_load) File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load for translation_strings in await asyncio.gather( File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task return await task File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration integration = await _async_get_integration(hass, domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration raise IntegrationNotFound(domain) homeassistant.loader.IntegrationNotFound: Integration 'n' not found.
```

**Comment by nielsfaber** [comment]
Sorry guys, there has been some breaking change in HA which hasn't been mentioned in their release notes or developer blog. 
It seems to be related to the translations used for the wildcard texts in notifications.
I will make a fix for it in a next release.

**Comment by sgoudelis** [comment]
I have the same issue, actions dont seem to work. Is this gonna get fixed soon ? I am sort of relying on this being a home alarm system and all.

**Comment by nielsfaber** [comment]
@sgoudelis You can revert to HA 2022.5 for the time being.
HA releases often come with (unannounced) breaking changes, I cannot prevent stuff from breaking. 
If you don't like this, it's better to hold off from brand new updates.

Anyway, I already have things working again locally and expect to make a new release in the upcoming weekend.
Just bear in mind that I'm just an individual who just maintains this project in his free time.

**Comment by sgoudelis** [comment]
Cool! Thank you very much!

**Comment by artursoler** [comment]
I had the same issue. For anyone else interested, my temporary workaround was to remove the template variables from the notifications. Notifications without variables still work fine.

**Comment by RACAT3** [comment]
I have narrowed this down to only away mode works with triggering alarm outputs like siren and alerts. Home, Night, Custom all do not trigger alerts or alarm outputs (siren).

**Comment by nielsfaber** [comment]
This issue should be solved by updating to v1.9.4. 
@Strangehadron: please close the issue after confirming the problem is solved.

**Comment by Strangehadron** [comment]
> This issue should be solved by updating to v1.9.4.
> @Strangehadron: please close the issue after confirming the problem is solved.

Thanks for your work, notifications and actions are now working as expected with the 1.9.4 update.
Thank you Niels !

**Comment by RACAT3** [comment]
I am not seeing an update avail in HA. Do we have to manually update it? If so how? Thank you again for updating so fast to correct the issues.

**Comment by nielsfaber** [comment]
@RACAT3 Alarmo is not included in HA. Most people use HACS for managing 3rd party plugins. It saves quite some trouble with manually downloading, unzipping and overwriting files. 
See the readme for updating instructions.
