### ISSUE TITLE
I coudn' change between armed home, away or night. The alarm_control_panel.xyz does not support this service.

### ISSUE THREAD

**Issue by pschyrembel258** [nielsfaber/alarmo#573]
### Alarmo Version

v1.9.5

### HA Version

2022.9.1

### Bug description

Yesterday I recognized that my automations depending on the Alarmo control panel and states doesn't work anymore. The states were triggered by the state of zone.home. if zero then arm.away, if 1 arm.home. First of all I thought it might be because of the new automations UI. But all my other automations still work perfectly. I tried the to switch the state of the alarm control panel manually and nothing happens. I found then the error in the log postet below. It says alarm_control_panel.xyz does not support this service. I restarted HA several times.

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:653 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:31:50 (3 occurrences) 
Last logged: 11:34:08

[281472410755680] Entity alarm_control_panel.casa_mehne does not support this service.
[281472441578688] Entity alarm_control_panel.casa_mehne does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 653, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.casa_mehne does not support this service.
```

**Comment by pschyrembel258** [comment]
I've reinstalled Alarmo, now it works again
