### ISSUE TITLE
Alarmo not loading since upgrading to 1.9.5

### ISSUE THREAD

**Issue by sh00t2kill** [nielsfaber/alarmo#588]
### Alarmo Version

v1.9.5

### HA Version

2022.09.7

### Bug description

Alarmo component does not load.

### Relevant log output

```shell
2022-10-02 23:32:01.070 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 55, in async_setup_entry
    store = await async_get_registry(hass)
  File "/config/custom_components/alarmo/store.py", line 687, in async_get_registry
    return cast(AlarmoStorage, await task)
  File "/config/custom_components/alarmo/store.py", line 682, in _load_reg
    await registry.async_load()                                                                                                                                          File "/config/custom_components/alarmo/store.py", line 312, in async_load                                                                                                data = await self._store.async_load()                                                                                                                                File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load                                                                                  return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 170, in _async_load_data                                                                            stored = await self._async_migrate_func(data["version"], data["data"])
  File "/config/custom_components/alarmo/store.py", line 228, in _async_migrate_func
    data["automations"] = [
  File "/config/custom_components/alarmo/store.py", line 230, in <listcomp>
    **parse_automation_entry({                                                                                                                                           File "/config/custom_components/alarmo/store.py", line 191, in parse_automation_entry                                                                                    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
  File "/config/custom_components/alarmo/store.py", line 191, in <lambda>
    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
TypeError: ActionEntry.__init__() got an unexpected keyword argument 'service_data'
```

**Comment by sh00t2kill** [comment]
Component loads when rolling back to 1.9.1
Its configured by the UI and not YAML, the only thing i could see re service_data mentioned yaml.

**Comment by nielsfaber** [comment]
I think this is the same problem as described in https://github.com/nielsfaber/alarmo/issues/538
A solution/workaround has also been discussed there. 
Could you check it out and see if you can solve it in the same way?

**Comment by sh00t2kill** [comment]
Yeah - same issue. I made a configuration change and then upgraded and everything is fine.

Apologies, i did look through existing issues, but only open ones, not closed.
