### ISSUE TITLE
Cannot activate alarmo at all anymore

### ISSUE THREAD

**Issue by jvuotila** [nielsfaber/alarmo#674]
### Alarmo Version

v1.9.7

### HA Version

2023.3.1

### Bug description

No errors when trying to activate alarmo. But when trying to disarm alarms got log below.

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:663
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:43:48 (6 occurrences)
Last logged: 19:00:06

[547372853248] Entity alarm_control_panel.alarmo does not support this service.
[547372088192] Entity alarm_control_panel.alarmo does not support this service.
[547370654768] Entity alarm_control_panel.alarmo does not support this service.
[547369685136] Entity alarm_control_panel.alarmo does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.alarmo does not support this service.
```

**Comment by jvuotila** [comment]
Just found the problem. On of the sensors is unavailable so whole alarm system is broken because of that.
