### ISSUE TITLE
Bug ? - Siren got off when disarming

### ISSUE THREAD

**Issue by cokeman0** [nielsfaber/alarmo#70]
Hi,

As promised, log from when disarming the alarm, and the siren goes off for 0,5 sec.

`2020-12-16 21:53:34 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_arm_away
2020-12-16 21:53:34 DEBUG (MainThread) [custom_components.alarmo.automations] state is updated from disarmed to arming
2020-12-16 21:53:34 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607471821
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.window_bedroom_720 changed: old_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=False, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>, new_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=True, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_back_597 changed: old_state=<state binary_sensor.door_back_597=off; battery_level=100, device_armed=False, last_tripped_time=2020-12-16T18:26:11+00:00, device_tripped=False, Vera Device Id=597, friendly_name=Door Back, device_class=door @ 2020-12-16T20:50:32.306615+01:00>, new_state=<state binary_sensor.door_back_597=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-16T18:26:11+00:00, device_tripped=False, Vera Device Id=597, friendly_name=Door Back, device_class=door @ 2020-12-16T20:50:32.306615+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_front_545 changed: old_state=<state binary_sensor.door_front_545=off; battery_level=1, device_armed=False, last_tripped_time=2020-12-16T08:20:23+00:00, device_tripped=False, Vera Device Id=545, friendly_name=Door Front, device_class=door @ 2020-12-16T20:50:32.303193+01:00>, new_state=<state binary_sensor.door_front_545=off; battery_level=1, device_armed=True, last_tripped_time=2020-12-16T08:20:23+00:00, device_tripped=False, Vera Device Id=545, friendly_name=Door Front, device_class=door @ 2020-12-16T20:50:32.303193+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.motion_diningroom_539 changed: old_state=<state binary_sensor.motion_diningroom_539=on; battery_level=100, device_armed=False, last_tripped_time=2020-12-16T20:43:44+00:00, device_tripped=True, Vera Device Id=539, friendly_name=Motion Diningroom, device_class=motion @ 2020-12-16T21:43:43.857438+01:00>, new_state=<state binary_sensor.motion_diningroom_539=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-16T20:53:34+00:00, device_tripped=False, Vera Device Id=539, friendly_name=Motion Diningroom, device_class=motion @ 2020-12-16T21:53:35.621341+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.motion_walk_though_20107 changed: old_state=<state binary_sensor.motion_walk_though_20107=off; battery_level=100, device_armed=False, last_tripped_time=2020-12-16T14:30:08+00:00, device_tripped=False, Vera Device Id=20107, friendly_name=Motion walk though , device_class=motion @ 2020-12-16T20:50:32.316998+01:00>, new_state=<state binary_sensor.motion_walk_though_20107=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-16T14:30:08+00:00, device_tripped=False, Vera Device Id=20107, friendly_name=Motion walk though , device_class=motion @ 2020-12-16T20:50:32.316998+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.window_lilli_right_564 changed: old_state=<state binary_sensor.window_lilli_right_564=off; battery_level=63, device_armed=False, last_tripped_time=2020-12-15T15:28:02+00:00, device_tripped=False, Vera Device Id=564, friendly_name=Window Lilli Right, device_class=window @ 2020-12-16T20:50:32.304629+01:00>, new_state=<state binary_sensor.window_lilli_right_564=off; battery_level=63, device_armed=True, last_tripped_time=2020-12-15T15:28:02+00:00, device_tripped=False, Vera Device Id=564, friendly_name=Window Lilli Right, device_class=window @ 2020-12-16T20:50:32.304629+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.window_lilli_left_557 changed: old_state=<state binary_sensor.window_lilli_left_557=off; battery_level=71, device_armed=False, last_tripped_time=2020-11-28T15:55:56+00:00, device_tripped=False, Vera Device Id=557, friendly_name=Window Lilli Left, device_class=window @ 2020-12-16T20:50:32.303892+01:00>, new_state=<state binary_sensor.window_lilli_left_557=off; battery_level=71, device_armed=True, last_tripped_time=2020-11-28T15:55:56+00:00, device_tripped=False, Vera Device Id=557, friendly_name=Window Lilli Left, device_class=window @ 2020-12-16T20:50:32.303892+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_master_bedroom_862 changed: old_state=<state binary_sensor.door_master_bedroom_862=off; battery_level=55, device_armed=False, last_tripped_time=2020-10-24T15:55:08+00:00, device_tripped=False, Vera Device Id=862, friendly_name=Door Master Bedroom, device_class=door @ 2020-12-16T20:50:32.312301+01:00>, new_state=<state binary_sensor.door_master_bedroom_862=off; battery_level=55, device_armed=True, last_tripped_time=2020-10-24T15:55:08+00:00, device_tripped=False, Vera Device Id=862, friendly_name=Door Master Bedroom, device_class=door @ 2020-12-16T20:50:32.312301+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_garden_523 changed: old_state=<state binary_sensor.door_garden_523=off; battery_level=100, device_armed=False, last_tripped_time=2020-12-14T22:25:25+00:00, device_tripped=False, Vera Device Id=523, friendly_name=døren ud til haven, device_class=door @ 2020-12-16T20:50:32.301650+01:00>, new_state=<state binary_sensor.door_garden_523=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-14T22:25:25+00:00, device_tripped=False, Vera Device Id=523, friendly_name=døren ud til haven, device_class=door @ 2020-12-16T20:50:32.301650+01:00>
2020-12-16 21:53:35 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.motion_kitchen_855 changed: old_state=<state binary_sensor.motion_kitchen_855=off; battery_level=100, device_armed=False, last_tripped_time=2020-12-16T18:38:08+00:00, device_tripped=False, Vera Device Id=855, friendly_name=Motion Kitchen, device_class=motion @ 2020-12-16T20:50:32.311412+01:00>, new_state=<state binary_sensor.motion_kitchen_855=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-16T18:38:08+00:00, device_tripped=False, Vera Device Id=855, friendly_name=Motion Kitchen, device_class=motion @ 2020-12-16T20:50:32.311412+01:00>
2020-12-16 21:54:04 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] async_leave_timer_finished
2020-12-16 21:54:04 DEBUG (MainThread) [custom_components.alarmo.automations] state is updated from arming to armed_away
2020-12-16 21:54:04 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607431658
2020-12-16 21:54:09 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.presence_4 changed: old_state=<state binary_sensor.presence_4=on; on=True, temperature=30.0, friendly_name=Motion Sensor - Mellem gang, device_class=motion @ 2020-12-16T21:52:07.355325+01:00>, new_state=<state binary_sensor.presence_4=off; on=True, temperature=30.0, friendly_name=Motion Sensor - Mellem gang, device_class=motion @ 2020-12-16T21:54:09.542357+01:00>
2020-12-16 21:54:09 DEBUG (MainThread) [custom_components.alarmo.automations] state is updated from armed_away to pending
2020-12-16 21:54:09 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607711884
2020-12-16 21:54:14 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall light.turn_off (c:84b7945d3948321130639cf89f3d50f3): entity_id=['group.all_lights']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 94, in _ensure_connected
    await asyncio.wait_for(self.connection.ensure_connection(), 10)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/light.py", line 120, in async_turn_off
    await self.async_put_characteristics({CharacteristicsTypes.ON: False})
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 96, in async_put_characteristics
    return await self._accessory.put_characteristics(payload)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 419, in put_characteristics
    results = await self.pairing.put_characteristics(characteristics)
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 250, in put_characteristics
    await self._ensure_connected()
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 96, in _ensure_connected
    raise AccessoryDisconnectedError(
2020-12-16 21:54:21 WARNING (MainThread) [homeassistant.components.sonos.media_player] Timeout waiting for target groups [[<Entity Køkken: paused>, <Entity Spisestue: paused>]]
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.window_bedroom_720 changed: old_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=True, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>, new_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=False, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.automations] state is updated from pending to triggered
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607521256
2020-12-16 21:54:25 ERROR (MainThread) [homeassistant.helpers.service] Invalid config for calling service: invalid template (TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.) for dictionary value @ data['data']
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607525149
2020-12-16 21:54:25 ERROR (MainThread) [homeassistant.helpers.service] Invalid config for calling service: invalid template (TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.) for dictionary value @ data['data']
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1608143606
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_back_597 changed: old_state=<state binary_sensor.door_back_597=off; battery_level=100, device_armed=True, last_tripped_time=2020-12-16T18:26:11+00:00, device_tripped=False, Vera Device Id=597, friendly_name=Door Back, device_class=door @ 2020-12-16T20:50:32.306615+01:00>, new_state=<state binary_sensor.door_back_597=off; battery_level=100, device_armed=False, last_tripped_time=2020-12-16T18:26:11+00:00, device_tripped=False, Vera Device Id=597, friendly_name=Door Back, device_class=door @ 2020-12-16T20:50:32.306615+01:00>
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.door_front_545 changed: old_state=<state binary_sensor.door_front_545=off; battery_level=1, device_armed=True, last_tripped_time=2020-12-16T08:20:23+00:00, device_tripped=False, Vera Device Id=545, friendly_name=Door Front, device_class=door @ 2020-12-16T20:50:32.303193+01:00>, new_state=<state binary_sensor.door_front_545=off; battery_level=1, device_armed=False, last_tripped_time=2020-12-16T08:20:23+00:00, device_tripped=False, Vera Device Id=545, friendly_name=Door Front, device_class=door @ 2020-12-16T20:50:32.303193+01:00>
2020-12-16 21:54:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
2020-12-16 21:54:26 DEBUG (MainThread) [custom_components.alarmo.automations] state is updated from triggered to disarmed
2020-12-16 21:54:26 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607524974
2020-12-16 21:54:26 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1607763053
`

**Comment by nielsfaber** [comment]
For next time, please use
````
```
( my code )
```
````
for readability.

**Comment by nielsfaber** [comment]
21:54:04 -> the alarm is armed an an automation is executed.
21:54:09 -> motion sensor activated, alarm goes to pending
21:54:14 -> errors due to a wrongly configured automation for `group.all_lights`.
21:54:21 -> errors due to sonos Køkken being unresponsive
21:54:25 -> window sensor bedroom updated and alarm is triggered, again 2x a wrongly configured automation

The log shows a lot of errors in your automations.
Although they shouldn't be the real problem, i suggest you to look at them (i cannot help you with that).

The main problem seems to be:
```
entity binary_sensor.window_bedroom_720 changed: old_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=True, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>, new_state=<state binary_sensor.window_bedroom_720=off; battery_level=100, device_armed=False, last_tripped_time=2020-10-25T21:48:21+00:00, device_tripped=False, Vera Device Id=720, friendly_name=Window bedroom, device_class=window @ 2020-12-16T20:50:32.307318+01:00>
```
Your Vera system seems to change the configuration for your door sensors at this moment (it sets a `device_armed=False` property)
Although the window remains closed, it seems to be causing problems.

I think this is a bug in my code.
I will investigate.

**Comment by nielsfaber** [comment]
I would like to ask you to update to v1.4.1 and test if this solves the problem.

**Comment by cokeman0** [comment]
That was the fix 👍 
Thanks
