### ISSUE TITLE
HA Alarm sends "Connection lost" info when wrong code is inserted

### ISSUE THREAD

**Issue by nbranquinho** [nielsfaber/alarmo#777]
### Alarmo Version

V1.9.10

### HA Version

2023.07.1

### Bug description

When the alarm is armed and when we try to enter a wrong code to disarm it, I get a notification from HA saying "Failed to call service alarm_control_panel/alarm_disarm. Connection Lost"
When you were supposed to receive the indication that the code was wrong.

### Steps to reproduce

with the alarm armed, introduce a wrong code to disarme it.

### Relevant log output

```shell
HA logs:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/manual/alarm_control_panel.py", line 289, in async_alarm_disarm
    self._async_validate_code(code, STATE_ALARM_DISARMED)
  File "/usr/src/homeassistant/homeassistant/components/manual/alarm_control_panel.py", line 380, in _async_validate_code
    raise HomeAssistantError("Invalid alarm code provided")
homeassistant.exceptions.HomeAssistantError: Invalid alarm code provided
```

**Comment by nbranquinho** [comment]
![image](https://github.com/nielsfaber/alarmo/assets/2866871/02d187ce-5ee7-44d9-ac5e-2b196f0a3bab)

**Comment by nielsfaber** [comment]
I think this issue is specific to your setup.
The 'connection lost' message speaks for itself: the connection between the webserver and the HA core was interrupted during the process.
I don't think there is any bug bug here.

Note that the alarm-panel card is part of HA itself, I don't maintain it.
You might want to install the alarmo-card instead.
