### ISSUE TITLE
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1655843481', 'armed_away', 'disarmed') 

### ISSUE THREAD

**Issue by ferrarid61** [nielsfaber/alarmo#780]
### Alarmo Version

 v1.9.10

### HA Version

2023.7.3

### Bug description

After upgrading to HA 2023.7 actions related to event disarmed don't work anymore.  The Ha logs reports "Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1655843481', 'armed_away', 'disarmed') " 

### Steps to reproduce

Everithing was working before upgrade. If I  use the test function inside the action, il works

### Relevant log output

```shell
Logger: homeassistant.util.logging
Source: util/logging.py:156
First occurred: 1 agosto 2023 alle ore 12:41:05 (12 occurrences)
Last logged: 23:07:13

Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1655843481', 'armed_away', 'disarmed') Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 310, in request return await req.result ^^^^^^^^^^^^^^^^ asyncio.exceptions.CancelledError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 120, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 215, in async_execute_automation await self.hass.async_create_task( File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service return await cast( ^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service return await service.entity_service_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call response_data = task.result() # pop exception if have ^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call return await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/zha/siren.py", line 161, in async_turn_off await self._cluster_handler.issue_start_warning( File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/security.py", line 330, in issue_start_warning await self.start_warning( File "/usr/local/lib/python3.11/site-packages/zigpy/util.py", line 132, in retry return await func() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 375, in request return await self._endpoint.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 253, in request return await self.device.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 309, in request async with asyncio_timeout(timeout): File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__ raise TimeoutError from exc_val TimeoutError
```

**Comment by nielsfaber** [comment]
> After upgrading to HA 2023.7 actions related to event disarmed don't work anymore. The Ha logs reports "Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1655843481', 'armed_away', 'disarmed') "

This issue does not occur for me.
I think it is specific to your configuration.

Perhaps an automation or notification is configured for an entity which doesn't exist anymore?

I cannot read the log you shared, all info is in a single line.
Please fix that if you expect any assistance on this.

I suggest to temporarily disable your existing automations and try again, just to pinpoint to the issue.

**Comment by ferrarid61** [comment]
Thank you for you answare. Probably I foud the problem. I have a zigbee device, siren, not working properly. In fact if you look at the log, at the very end it reports a timeout and exit the procedure.
The problem is the some other automations triggered by the same events don't compete because all the actions flows  exit entierly because ofthe timeout of a single action. 
Does it make sense ?
The single line log is the way ha report log traceback. Anyway I tried to decode as follows.

Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1655843481', 'armed_away', 'disarmed')
Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 310, in request return await req.result ^^^^^^^^^^^^^^^^ asyncio.exceptions.
CancelledError The above exception was the direct cause of the following exception:
Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 120, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity)
File "/config/custom_components/alarmo/automations.py", line 215, in async_execute_automation await self.hass.async_create_task( File "/usr/src/homeassistant/homeassistant/core.py", line 1965,
in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2005,
in _execute_service return await cast( ^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235,
in handle_service return await service.entity_service_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848,
in entity_service_call response_data = task.result()
# pop exception if have ^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192,
in async_request_call return await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892,
in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/zha/siren.py", line 161,
in async_turn_off await self._cluster_handler.issue_start_warning( File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/security.py", line 330,
in issue_start_warning await self.start_warning( File "/usr/local/lib/python3.11/site-packages/zigpy/util.py", line 132,
in retry return await func() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py",line 375,
in request return await self._endpoint.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 253,
in request return await self.device.request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 309,
in request async with asyncio_timeout(timeout): File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111,
in __aexit__ raise TimeoutError from exc_val TimeoutError

**Comment by ferrarid61** [comment]
> This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days

I replied giving an explanation of the problem. Again if some problem happend in some action the sequence bloks. Is something inside Alarmo automation

**Comment by nielsfaber** [comment]
The error log you shared mentions a timeout in a zigbee device.
So it seems you are controlling some zigbee (ZHa) device (siren) via automation, and it fails to respond.
So I think the issue is not related to alarmo, but it occurs on the zigbee device or controller.
