### ISSUE TITLE
Alarmo no longer available on v.1.9.12

### ISSUE THREAD

**Issue by sambarlick** [nielsfaber/alarmo#830]
### Alarmo Version

1.9.12

### HA Version

2023.11.0

### Bug description

After updating to 1.9.12 the integration is no longer available. Reverting to 1.9.10 fixes the issue.

### Steps to reproduce

Update to 1.9.12

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 16:23:24 (1 occurrences)
Last logged: 16:23:24

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 682, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 677, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 306, in async_load
    data = await self._store.async_load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 133, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 142, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 243, in _async_load_data
    stored = await self._async_migrate_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 282, in _async_migrate_func
    data["config"] = attr.asdict(Config(
                                 ^^^^^^^
TypeError: custom_components.alarmo.store.Config() got multiple values for keyword argument 'code_mode_change_required'
```

**Comment by nielsfaber** [comment]
See https://github.com/nielsfaber/alarmo/issues/822

**Comment by sambarlick** [comment]
After removing the integration, rebooting Home Assistant, reinstalling the integration, restating and adding the integration it still has the same errors.

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 19:12:10 (1 occurrences)
Last logged: 19:12:10

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 682, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 677, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 306, in async_load
    data = await self._store.async_load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 133, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 142, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 243, in _async_load_data
    stored = await self._async_migrate_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 282, in _async_migrate_func
    data["config"] = attr.asdict(Config(
                                 ^^^^^^^
TypeError: custom_components.alarmo.store.Config() got multiple values for keyword argument 'code_mode_change_required'

**Comment by sambarlick** [comment]
I opened the alarmo.storage file and there is only 1 instance of code_mode_change_required.

**Comment by rt400** [comment]
try to remove this line : 
```
"code_mode_change_required": true,
```
restart to HA and see if its work.
that work for me...

**Comment by sambarlick** [comment]
Mine is currently set to false. Should I remove it anyway?

**Comment by rt400** [comment]
yes.
