### ISSUE TITLE
Setup keeps  failing

### ISSUE THREAD

**Issue by excalbian** [nielsfaber/alarmo#839]
### Alarmo Version

v1.9.13

### HA Version

2023.11.1

### Bug description

Alarmo started failing after I upgraded to HA 2023.11. I've tried removing the  integration, restarting, and then re-adding it, to no avail.

### Steps to reproduce

1. Installed custom component
2. Restart HA
3. Add device
4. Setup failed :(
![image](https://github.com/nielsfaber/alarmo/assets/242196/997396e1-3cd2-4ecf-8a38-665ca7b91cd9)

### Relevant log output

```shell
Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 682, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 677, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 306, in async_load
    data = await self._store.async_load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 133, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 142, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 243, in _async_load_data
    stored = await self._async_migrate_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 282, in _async_migrate_func
    data["config"] = attr.asdict(Config(
                                 ^^^^^^^
TypeError: Config.__init__() got an unexpected keyword argument 'trigger_time'
```

**Comment by nielsfaber** [comment]
I recommend deleting the alarmo.storage file in the .storage subfolder in the HA configuration directory.
Uninstalling the integration should have the same effect but for some reason that didn’t work for you.

**Comment by excalbian** [comment]
Thank you! Deleting `config/.storage/alarmo.storage` did the trick and now my Alarmo integration is working again.
