### ISSUE TITLE
cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core'

### ISSUE THREAD

**Issue by jjordanarenas** [nielsfaber/alarmo#902]
### Alarmo Version

v1.9.9

### HA Version

2024.2.5

### Bug description

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alarmo/__init__.py", line 39, in <module>
    from .automations import AutomationHandler
  File "/config/custom_components/alarmo/automations.py", line 5, in <module>
    from homeassistant.core import (
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

### Steps to reproduce

Just starting Home Assistant triggers this issue

**Comment by nielsfaber** [comment]
Update alarmo.
