### ISSUE TITLE
New error after updating to Core2024.3.0

### ISSUE THREAD

**Issue by joe7045** [nielsfaber/alarmo#905]
### Alarmo Version

v1.9.14

### HA Version

2024.3.0

### Bug description

After restart HA, consulting logs always appear an error message. 
Expected to solve the error message.
Alarm works correctly

### Steps to reproduce

This error appears each time HA is restarted

### Relevant log output

```shell
After restart HA, consulting logs always appear:
Registrador: homeassistant.util.logging
Fuente: util/logging.py:102
Ocurrió por primera vez: 07:50:06 (3 ocurrencias)
Último inicio de sesión: 07:50:06

Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1680611239', None, 'disarmed') Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 61, in async_alarm_state_changed if not self._config[ATTR_MQTT][const.ATTR_ENABLED] or not new_state: ~~~~~~~~~~~~^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1681810307', None, 'disarmed') Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 61, in async_alarm_state_changed if not self._config[ATTR_MQTT][const.ATTR_ENABLED] or not new_state: ~~~~~~~~~~~~^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1698671164', None, 'disarmed') Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 61, in async_alarm_state_changed if not self._config[ATTR_MQTT][const.ATTR_ENABLED] or not new_state: ~~~~~~~~~~~~^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
```

**Comment by markieo1** [comment]
This is duplicated by #899

**Comment by nielsfaber** [comment]
Update your alarmo installation to fix the issue.

**Comment by joe7045** [comment]
Done!
Error has gone. Great job
Thank you a lot
