### ISSUE TITLE
Notification variable missing

### ISSUE THREAD

**Issue by eddiebullman** [nielsfaber/alarmo#912]
### Alarmo Version

v1.9.15

### HA Version

2024.3.3

### Bug description

Google Translate Say Notification doesn't say the variable information e.g Home or Away when being set.

Screen Shot of settings
![Screenshot 2024-03-23 at 14 53 47](https://github.com/nielsfaber/alarmo/assets/78513296/6f43ef4e-dba7-40d6-8ff2-b99416527df0)

### Steps to reproduce

Deleted and recreate notification with same result

### Relevant log output

```shell
Logger: homeassistant.core
Source: core.py:2335
First occurred: 15:09:42 (1 occurrences)
Last logged: 15:09:42

Error executing service: <ServiceCall tts.google_translate_say (c:01HSNXRJNARG5096Z6RXYQDK19): message=The alarm is set to , entity_id=['media_player.lounge_homepod_mini']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2335, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/legacy.py", line 148, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 343, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.12/site-packages/pyatv/core/facade.py", line 371, in stream_file
    await self.relay("stream_file")(
  File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/raop/__init__.py", line 345, in stream_file
    self.playback_manager.acquire()
  File "/usr/local/lib/python3.12/site-packages/pyatv/protocols/raop/__init__.py", line 133, in acquire
    raise exceptions.InvalidStateError("already streaming to device")
pyatv.exceptions.InvalidStateError: already streaming to device
```

**Comment by nielsfaber** [comment]
The error states 'already streaming to device'. This has nothing to do with alarmo, but with your device.
