### ISSUE TITLE
Cannot disable alarm through HA control panel or automation

### ISSUE THREAD

**Issue by alexstaal** [nielsfaber/alarmo#968]
### Alarmo Version

v1.10.1

### HA Version

2024.6.1

### Bug description

When disarming the alarm through the Home Assistant control panel (more info dialog of the alarm entity) or when disarming through an automation. I get this error.

When disarming through the alarmo frontend card, no error and i can disarm

### Steps to reproduce

Arm the alarm, then disarm through HA control panel 

Or automation:
`device_id: some-id
domain: alarm_control_panel
entity_id: alarm_control_panel.alarmo
type: disarm
code: "blaat"`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 207, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
```

**Comment by nielsfaber** [comment]
I don’t accept bug reports for older version of alarmo.
