### ISSUE TITLE
enable/disable no longer possible after update to 2024.6.1

### ISSUE THREAD

**Issue by TheChosenOne1984** [nielsfaber/alarmo#972]
### Alarmo Version

v1.10.0

### HA Version

2024.6.1

### Bug description

After updating to 2024.6.1 its no longer possible to enable or disable the alarm.
Not via a control panel in the browser gui or android app and also not via sonoff nspanel (esphome).

If you need further information, let me know.

Thanks a lot!

### Steps to reproduce

Try to enable or disable the alarm.
The attached error message is shown.

![alarmo_1](https://github.com/nielsfaber/alarmo/assets/140900215/f6e0e236-7f8c-4884-b194-1ec4b19eed60)

### Relevant log output

```shell
2024-06-10 08:24:29.910 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwd_pollenflug which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.913 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration stadtreinigung_hamburg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.916 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.919 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pfsense_gateways which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.922 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dreame_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.923 ERROR (SyncWorker_0) [homeassistant.loader] Version v1.0.3 of custom integration 'dreame_vacuum' crashes Home Assistant and was blocked from loading, please create a bug report at https://github.com/Tasshack/dreame-vacuum/issues
2024-06-10 08:24:29.934 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zha_toolkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.938 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.942 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.945 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.949 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.952 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:24:29.957 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deutschebahn which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:25:14.882 ERROR (MainThread) [homeassistant.helpers.translation] Validation of translation placeholders for localized (de) string component.easee.device_automation.condition_type.error_pen_fault failed: (set() != {'entity_name'})
2024-06-10 08:25:14.883 ERROR (MainThread) [homeassistant.helpers.translation] Validation of translation placeholders for localized (de) string component.easee.device_automation.trigger_type.error_pen_fault failed: (set() != {'entity_name'})
2024-06-10 08:25:16.652 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-06-10 08:25:30.076 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2024-06-10 08:25:30.225 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /os/info request
2024-06-10 08:25:30.228 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /network/info request
2024-06-10 08:25:30.228 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /core/info request
2024-06-10 08:25:30.229 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /resolution/info request
2024-06-10 08:25:30.229 ERROR (MainThread) [homeassistant.components.hassio.issues] Failed to update supervisor issues: HassioAPIError()
2024-06-10 08:25:30.233 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /host/info request
2024-06-10 08:25:30.233 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /info request
2024-06-10 08:25:30.234 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/options request
2024-06-10 08:25:30.235 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /store request
2024-06-10 08:25:30.236 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/info request
2024-06-10 08:25:30.244 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /ingress/panels request
2024-06-10 08:25:30.244 ERROR (MainThread) [homeassistant.components.hassio.addon_panel] Can't read panel info: 
2024-06-10 08:25:30.249 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2024-06-10 08:25:36.547 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for update.home_assistant_supervisor_update (<class 'homeassistant.components.hassio.update.SupervisorSupervisorUpdateEntity'>) took 1.435 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+hassio%22
2024-06-10 08:25:37.486 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('hassio', 'a3e77c30516f7499dfa6869bad86d581'): 1470.026980743}
2024-06-10 08:27:02.816 WARNING (MainThread) [homeassistant.setup] Setup of stream is taking over 10 seconds.
2024-06-10 08:27:29.284 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('mqtt', '5d1faff9180f26ad3d968dda980e09a2'): 1582.052099341, ('shopping_list', 'ec8de7b5d388812b679fea3656f4b600'): 1582.053114308, ('dwd_pollenflug', '1c8ff16c83d2dce09e8cdcec21a7daec'): 1582.129156708, ('co2signal', 'f649a9fb75e8e1e14f479c6813af10f7'): 1582.321420592, ('hue', 'f25d5ad6e645b799c2a63a56219d096f'): 1583.803073117, ('dlna_dmr', 'd54973172d30ed4e75b94c08b9ec98cc'): 1584.064204338, ('androidtv_remote', '366564a279ddfc6512b35759d8617bd2'): 1586.607967957}
2024-06-10 08:27:57.060 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-10 08:28:32.622 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('mqtt', '5d1faff9180f26ad3d968dda980e09a2'): 1582.052099341, ('shopping_list', 'ec8de7b5d388812b679fea3656f4b600'): 1582.053114308, ('dwd_pollenflug', '1c8ff16c83d2dce09e8cdcec21a7daec'): 1582.129156708, ('co2signal', 'f649a9fb75e8e1e14f479c6813af10f7'): 1582.321420592, ('hue', 'f25d5ad6e645b799c2a63a56219d096f'): 1583.803073117, ('dlna_dmr', 'd54973172d30ed4e75b94c08b9ec98cc'): 1584.064204338, ('androidtv_remote', '366564a279ddfc6512b35759d8617bd2'): 1586.607967957, ('denonavr', 'c491be0f63a45821bd8f38f3dfd5fe49'): 1592.83399082, ('met', '1ab59c748c69365c2e07bf56e2ecf8a6'): 1593.094399646, ('google_translate', 'df89738250bb9c08d7f353e4fe86b7c9'): 1593.151610712, ('webostv', 'bbcdf2b448008f6a0a2b8402dc97af85'): 1600.67386404, ('hacs', '3e22301cabb6727e8cf997f7492f0799'): 1615.290084438, ('xiaomi_miio', 'd7c37c8be987878aa82faf67224c954b'): 1634.99798039, ('xiaomi_miio', '4ad8a616b69a7391e24ab2736bc872a4'): 1634.998846451, ('frontier_silicon', 'ab079f90000008827031d2f474d5b93c'): 1635.332240721, ('brother', 'b9ef06fb52e6a7b255de9dc7f21937d0'): 1643.177558913}
2024-06-10 08:29:05.531 WARNING (SyncWorker_0) [homeassistant.components.homematic.sensor] Sensor (Sirene ARMSTATE) entity description is missing. Sensor state (ARMSTATE) needs to be maintained
2024-06-10 08:29:05.532 WARNING (SyncWorker_0) [homeassistant.components.homematic.sensor] Sensor (Sirene Keller ARMSTATE) entity description is missing. Sensor state (ARMSTATE) needs to be maintained
2024-06-10 08:29:15.483 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform homematic is taking over 10 seconds.
2024-06-10 08:29:15.516 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform homematic is taking over 10 seconds.
2024-06-10 08:29:23.154 WARNING (SyncWorker_9) [homeassistant.helpers.frame] Detected that custom integration 'alarmo' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/alarmo/sensors.py, line 175: self._state_listener = async_track_state_change(, please report it to the author of the 'alarmo' custom integration
2024-06-10 08:29:23.860 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in async_watch_sensor_states when dispatching 'alarmo_state_updated': (None, None, 'disarmed')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/sensors.py", line 172, in async_watch_sensor_states
    self._state_listener()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 390, in _remove_listener
    callbacks[key].remove(job)
ValueError: list.remove(x): x not in list

2024-06-10 08:31:51.674 WARNING (ImportExecutor_0) [homeassistant.const] DEVICE_CLASS_TIMESTAMP was used from stadtreinigung_hamburg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TIMESTAMP instead, please report it to the author of the 'stadtreinigung_hamburg' custom integration
2024-06-10 08:32:43.072 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from deutschebahn, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'deutschebahn' custom integration
2024-06-10 08:32:44.605 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-10 09:34:56.610 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620879064816] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 959, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.erdgeschoss does not support this service.
2024-06-10 09:35:27.135 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620879064816] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 959, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.erdgeschoss does not support this service.
2024-06-10 09:36:01.101 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620879064816] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 959, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.erdgeschoss does not support this service.
```

**Comment by Omrizn** [comment]
You should call the service "alarmo.disarm" from now on and not alarm_control_panel.alarm_disarm

**Comment by TheChosenOne1984** [comment]
Hi Omrizn,

thanks for getting back on this!

How can I do this?

The control panel currently has this code for example:
```
states:
  - arm_away
type: alarm-panel
entity: alarm_control_panel.erdgeschoss
```

Also, if I have a look on my entities, they are still called like before
```
Dachgeschoss  alarm_control_panel.dachgeschoss
Erdgeschoss     alarm_control_panel.erdgeschoss
Keller                 alarm_control_panel.keller
Haus                  alarm_control_panel.haus
```

So what do I have to change to use alarmo.disarm on my different zones?

Also, was this change in the release notes and I've overseen it?

Thank you again and cheers

**Comment by nielsfaber** [comment]
Please share a screenshot of the mode settings for the ‘erdgeschoss’ area in alarmo and a screenshot of the properties of the corresponding alarm_control_panel entity in the Developer Tools - states panel.

**Comment by DWFerdie** [comment]
Same problem here :

"No se pudo llamar al servicio alarm_control_panel/alarm_disarm. AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given"

**Comment by TheChosenOne1984** [comment]
Hi Nils,

also thanks to you for supporting me here. Hopefully this is what you are looking for?

![alarmo_devtools](https://github.com/nielsfaber/alarmo/assets/140900215/bfc2b489-194c-4e6c-b9ed-ad3b8537c03f)
![alarmo_mode_eg](https://github.com/nielsfaber/alarmo/assets/140900215/5138c519-84cf-4bfb-9111-282bfce6d755)

**Comment by TheChosenOne1984** [comment]
Hi Nils,

I've put this to disabled this morning as I was not able to deactivate the alarm. I was hoping this would help and forgot to enable this again.
But even when I have this on enabled again, I still have trouble with disabling the alarm.
See my screenshot and the attached log.

![alarmo_DG_active_try_to_deactivate](https://github.com/nielsfaber/alarmo/assets/140900215/8608801e-d61d-48ef-a84e-1a4523ca0166)

```
2024-06-10 14:47:05.100 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620861735120] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 959, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.dachgeschoss does not support this service.
2024-06-10 14:48:26.727 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620861735120] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 207, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
2024-06-10 14:48:41.528 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620861735120] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 207, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
2024-06-10 14:51:39.889 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140620861735120] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 207, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
```

**Comment by nielsfaber** [comment]
@TheChosenOne1984 you can fix that issue yourself by updating alarmo. I don’t spend time on bug issues from users who use outdated versions.

**Comment by TheChosenOne1984** [comment]
@nielsfaber ,
sorry for the noise. I'm still new to the game and I forgot to look for available updates in HACS. I only checked in HA settings.
In fact, you supported me, and I'm really thankful you did.

So, sorry again and thank you!
