### ISSUE TITLE
single_instance_allowed

### ISSUE THREAD

**Issue by bentoooooo** [nielsfaber/alarmo#991]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.1

### Bug description

Removed Alarmo before updating to 2024.7.1, updated.
Now i'm trying to add it again and it shows the error:
"single_instance_allowed".
I don't have any instance...
Already tried to redownload it on hacs, and removing it (deleting can't be done with the error: "Integration is configured
The Alarmo integration is configured or ignored, you need to delete the configuration for it before removing it from HACS").
Again... No integration at all.

### Steps to reproduce

Remove Alarmo integration before updating to 2024.7.1
Update
Try to add it again.

### Relevant log output

```shell
No logs to this problem.
```

**Comment by polyar6688** [comment]
Hola. Tenia el MISMO Problema. Resulto que Tenia la INTEGRACION DESHABILITADA..
Filtra por integraciones Deshabilitadas, HABILITA Alarmo y SOLUCIONADO queda

**Comment by troycarpenter** [comment]
This is exactly where I'm stuck.  Here are the logs for this event:
```
2024-07-30 13:01:30.393 INFO (SyncWorker_53) [homeassistant.loader] Loaded panel_custom from homeassistant.components.panel_custom
2024-07-30 13:01:30.394 INFO (MainThread) [homeassistant.setup] Setting up panel_custom
2024-07-30 13:01:30.541 INFO (MainThread) [homeassistant.setup] Setting up alarmo
2024-07-30 13:01:30.547 INFO (MainThread) [homeassistant.helpers.storage] Migrating alarmo.storage storage from 6.1 to 6.3
2024-07-30 13:01:30.547 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alarmo/__init__.py", line 57, in async_setup_entry
store = await async_get_registry(hass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alarmo/store.py", line 689, in async_get_registry
return cast(AlarmoStorage, await task)
^^^^^^^^^^
File "/config/custom_components/alarmo/store.py", line 684, in _load_reg
await registry.async_load()
File "/config/custom_components/alarmo/store.py", line 314, in async_load
data = await self._store.async_load()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 289, in async_load
result = await self._async_load()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 309, in _async_load
return await self._async_load_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 412, in _async_load_data
stored = await self._async_migrate_func(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alarmo/store.py", line 279, in _async_migrate_func
data["config"] = attr.asdict(Config(
^^^^^^^
TypeError: Config.__init__() got an unexpected keyword argument 'trigger_time'
```
Because of this, the integration never sets up, then I get the error above.
![image](https://github.com/user-attachments/assets/fd06ed56-9c7c-427a-9c27-fa81cccf057b)

**Comment by MiguelViana7** [comment]
I am having the exact same issue

**Comment by troycarpenter** [comment]
> PS: Fixed it by going to Devices & Services - top right corner "Disabled Integrations" - Deleted Alarmo - Added Alarmo again

In my case, Alarmo isn't disabled.  It is enabled but says it can't set itself up.  Maybe this is the same error message for two separate issues.
