### ISSUE TITLE
Refusing to start

### ISSUE THREAD

**Issue by dougle03** [nielsfaber/alarmo#997]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.2

### Bug description

Fails to start (See log)

### Steps to reproduce

None, fails on boot

### Relevant log output

```shell
Logger: homeassistant.setup
Source: /usr/src/homeassistant/homeassistant/setup.py:269
First occurred: 10:05:06 (1 occurrences)
Last logged: 10:05:06

Setup failed for custom integration 'alarmo': Unable to import component: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alarmo/__init__.py", line 29, in <module>
    from .panel import (
  File "/config/custom_components/alarmo/panel.py", line 6, in <module>
    from homeassistant.components.http import StaticPathConfig
ImportError: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1004, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alarmo/__init__.py", line 29, in <module>
    from .panel import (
  File "/config/custom_components/alarmo/panel.py", line 6, in <module>
    from homeassistant.components.http import StaticPathConfig
ImportError: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)
```

**Comment by nielsfaber** [comment]
It seems you are not on HA 2024.7, please check

**Comment by dougle03** [comment]
Ahh ok, updating now. I don't tend to update until near the end of the month as .0 and .1's tend to be more buggy...

**Comment by dougle03** [comment]
Rebooted. All sorted. Thanks.
